import type { Metadata } from "next";
import localFont from 'next/font/local'
import style from '@/styles/tip.module.scss'

const myFont = localFont({
  src: '../../public/fonts/AppleSDGothicNeoEB.ttf',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className={style.root}>
          <div className={style.top}></div>
          <div className={style.main}>{children}</div> 
        </div>
      </body>
    </html>
  );
}
