import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import style from "@/styles/main.module.scss"
import Topbar from "./components/Topbar";
const myFont = localFont({
  src: '../public/fonts/AppleSDGothicNeoEB.ttf',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className={style.top}>
          <Topbar/>
        </div>
         {children}
      </body>
    </html>
  );
}
